server:
  port: 9000

spring:
  application:
    name: food-example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddd?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
